import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header/Header";
import axios from "axios";
import { TabProvider } from "./provider";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movies App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TabProvider>
            <Header />
            {children}
          </TabProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
